FROM nginx:alpine

COPY nginx.conf /etc/nginx/

RUN apk add --no-cache bash \
    && rm -rf /var/cache/apk/*

ARG PHP_UPSTREAM_CONTAINER=php-fpm
ARG PHP_UPSTREAM_PORT=9000

RUN echo "upstream php-upstream { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf \
  && rm /etc/nginx/conf.d/default.conf

COPY ./startup.prod.sh /opt/startup.sh
RUN chmod +x /opt/startup.sh

EXPOSE 80 443

CMD ["/bin/bash", "/opt/startup.sh"]
