version: "3.8"

services:
  nginx:
    build:
      context: "./docker/nginx"
      dockerfile: Dockerfile.prod
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/sites/prod/laravel.conf:/etc/nginx/conf.d/laravel.conf:ro
      - ./:/var/www/app:ro
      - ./docker/logs/nginx:/var/log/nginx # [OPSIONAL] Mount log nginx ke host jika ingin persist log
    restart: unless-stopped
    networks:
      - appnet

  php-fpm:
    build:
      context: "./docker/php-fpm"
      dockerfile: Dockerfile.prod
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - appnet
    expose:
      - "9000"  # [PROD ONLY] Port untuk komunikasi internal ke nginx
    depends_on:
      - pgsql
      - redis
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    restart: unless-stopped

  pgsql:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sail-pgsql:/var/lib/postgresql/data
    # - ./docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql # [DEV ONLY]
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - sail-redis:/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
